#!/bin/sh
#

[[ -e "/dashboard/project/.run-once" ]] && { sh /dashboard/project/.run-once; rm /dashboard/project/.run-once; }

[[ -e "/dashboard/project/.run" ]] && { sh /dashboard/project/.run; }

exec "$@"
